### ISSUE TITLE
Gsettings fails on exit

### ISSUE THREAD

**Issue by thenewnano** [jistr/ansible-gsetting#8]
When setting a value using ansible on ubuntu 18.04 and 18.10 the exit routine seems to not return pass, but the setting key actually changes 
`fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "", 
    "module_stdout": "{\"changed\": false, \"old_value\": \"false\", \"value\": \"false\", \"key\": \"org.gnome.desktop.media-handling.automount-open\"}\n{\"msg\": \"New-style module did not handle its own exit\", \"failed\": true}\n", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
`

**Comment by jistr** [comment]
Fixed in 4752bf648106d51b585f4c881feb0fac4c331774 but i forgot to close the issue earlier, doing so now.
